steps:
- label: ":docker: Build Golang Project"
  plugins:
  - docker#v5.11.0:
      image: "golang:1.18.0" # Docker image for building Go
      workdir: "/app" # Sets the working directory to /app in the container
  commands:
  - cd hello && go build -o hello # Runs inside the Docker container
  - buildkite-agent artifact upload "hello/hello" # Uploads binary as an artifact

- wait

- label: ":pause_button: Enter Your Name"
  type: block
  prompt: "Please enter your name"
  fields:
  - text: "name"
    key: "user_name"
    hint: "Enter your name"
    required: true

- label: ":run: Execute Program"
  plugins:
  - docker#v5.11.0:
      image: "alpine:latest" # Use a lightweight image for running the binary
      workdir: "/app"
  commands:
  - buildkite-agent artifact download "hello/hello" . # Download binary
  - chmod +x hello/hello # Ensure it's executable
  - |
    USER_NAME=$(buildkite-agent meta-data get "user_name") # Get user input
    ./hello/hello "$USER_NAME" # Run the program with user's name
